---
name: Format Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  format:
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: date +%W > weekly

      - name: Restore cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install stylua

      - name: Format
        run: stylua --check tests/ --config-path=.stylua.toml
